### ISSUE TITLE
POST /units/ and PATCH /units/{id_unit}/ are broken on the server

### ISSUE THREAD

**Issue by Neonsonne** [hitmeister/api-sdk-php#110]
I am not actually using the PHP SDK. I am simply trying the swagger ui on https://www.kaufland.de/api/v1/?page=endpoints. If I send a POST to /units/ with the following JSON

{
  "ean": "5050192667210",
  "condition": "new",
  "listing_price": 2399,
  "minimum_price": 2399
}

I get return code 400 
{
  "message": " : minimum price cannot be bigger than listing price"
}

I can use any minimum_price I want the result is always the same. The same is true for the PATCH api endpoint. Even if I only want to patch the amount of an existing item unit the result is " : minimum price cannot be bigger than listing price".

**Comment by benjaminsattler** [comment]
Hi @Neonsonne,

thanks for your report!

Please try this again and use integers for the fields `listing_price` and `minimum_price` (no quotes around the prices). Let me know if this solves your problem.

best,
Benjamin

**Comment by Neonsonne** [comment]
Hi,

thanks for your fast response. 

I tried by using integers, by setting minimum_price to 1, using a different EAN and many other different combinations. Still no luck. The response is always "minimum price cannot be bigger than listing price" for all POST and PATCH requests. Any other suggestions?

**Comment by benjaminsattler** [comment]
Hi @Neonsonne,

I have just tried to reproduce your problem with the API test page that we have available here: https://www.kaufland.de/api/v1/?page=endpoints#!/units/addUnit

In the screenshot you can see that I was able to successfully create the offer with the body that you posted (I had to modify the prices in order to not interfere with actual offers for this product):
![Screenshot 2021-06-30 at 2 53 16 PM](https://user-images.githubusercontent.com/10059547/123964077-61e98780-d9b3-11eb-8f48-89da86550dde.png)

Can you please try to do perform this action on this test client as well?

I think I need more information in order to be able to help you further. Can you maybe attach the raw HTTP request/response log including headers, encodings etcetc? **Please be sure to redact your API secrets and any other sensitive information in order not compromise your API access!**

best,
benjamin

**Comment by Neonsonne** [comment]
Hi,

I retried using your API test page and created a har file export in Chrome.
[www.kaufland.de.har.zip](https://github.com/hitmeister/api-sdk-php/files/6760343/www.kaufland.de.har.zip)

I removed the hm-* headers from the file. Here is a screenshot that shows the request as well.

<img width="975" alt="Screenshot" src="https://user-images.githubusercontent.com/1775326/124394731-0136b380-dd01-11eb-982c-2fc829ad6d64.png">

I guess the problem has something to do with a setting in our account. We already suspected the Tiefpreisautomatik feature may have something to do with this issue.

Any further ideas?

Regards,
Patrick

**Comment by benjaminsattler** [comment]
Hi @Neonsonne,

thanks for the data. There are 2 things that may affect the prices:

- Tiefstpreisautomatik
- any price adjustment that you may have defined in our account

Please check your account settings:
1. Login to sellerportal
2. Navigate to https://sellerportal.kaufland.de/imports/
3. In that page please look for "Price adjustments" or "Preisanpassungen" and change/remove those that affect your API

**Comment by benjaminsattler** [comment]
closed due to inactivity. please reopen if you need further assistance.
