### ISSUE TITLE
When will the API move to real.de

### ISSUE THREAD

**Issue by elipoultorak** [hitmeister/api-sdk-php#17]
When orders are made on real.de, can we see them in the hitmeister API?
Will the API's URLs change at some point?
Thanks

**Comment by Hanisch-IT** [comment]
real should already work with this api

**Comment by aazon** [comment]
Hello,

> When orders are made on real.de, can we see them in the hitmeister API?

Absolutely! Hitmeister API and Real API are the same application. After the move to www.real.de there are still a lot of sellers who use www.hitmeister.de as a hostname for their API requests even though they can use www.real.de.

The following URLs will return the same information:
`www.hitmeister.de/api/v1/orders/123/` == `www.real.de/api/v1/orders/123/`

Since we don't want to break their working integrations we support API to work under `www.hitmeister.de` as well. But for new API users we would suggest to use `www.real.de`.

Best Regards,
Alex

**Comment by elipoultorak** [comment]
Thanks
