### ISSUE TITLE
/orders/{id_order}/ Endpoint: faulty behaviour on real.de

### ISSUE THREAD

**Issue by michael-herwig** [hitmeister/api-sdk-php#25]
According to your [documentation](https://www.real.de/api/v1/?page=orders):

> To get the units in each order, you must query the orders individually via the /orders/{id_order}/ endpoint.

Im using your API on Real.DE but using the endpoint /orders/{id_order} just returns a single json object containing the fields id_order and ts_created. Didn't I understood something right? I thought the query should send me the appropriate order units related to the queried id_order.

I looked up your provided php SDK but couldn't find a hint for a function searching for order units with given id_order.

Regards,
Michael

**Comment by aazon** [comment]
Hello, Michael.

The short answer is: add GET parameter `?embedded=seller_units` to get a list of order units attached to the body.

More verbose answer:
Unless stated otherwise `/orders/{id_order}/ ` returns an order in a "minimal" size, i.e. only `id_order` and `ts_created` fields are included. However, there is a way to request some extra information -- by means of `GET` parameter called `embedded`. For the endpoint in question the valid values for this parameter are:

- billing_address
- buyer
- seller_units
- shipping_address

Thus to get an order with full possible information attached one needs to list all these values comma-separated: `/orders/{id_order}/?embedded=billing_address,buyer,seller_units,shipping_address`.

Hope this helps.
Alex.

**Comment by michael-herwig** [comment]
Hello, Alex.

This states everything very clearly. 

However I think the endpoint definition file `api-sdk-php/src/Endpoints/Orders/Get.php` misses the parameter definition? (I am not very familiar with php) Additionally knowing all accepted values for given parameters would help a lot for understanding your interface in more detail. Maybe you could consider updating your documentation accordingly.

I thank you very much for your fast response.
Michael

**Comment by aazon** [comment]
Michael,

There is a [page with all endpoints](https://www.real.de/api/v1/endpoints.html) where one can play with our API. Be careful, this is not a sandbox and in case of change, the production data will be affected.

Thanks a lot for your feedback, we'll improve our SDK as well.

Best Regards,
Alex
